const PLAYERS = [
  {
    first_name: "Tom",
    last_name: "Heaton",
    position: "Goalkeeper",
    nationality: "England",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Victor",
    last_name: "Lindelof",
    position: "Defender",
    nationality: "Sweden",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Harry",
    last_name: "Maguire",
    position: "Defender",
    nationality: "England",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Lisandro",
    last_name: "Martinez",
    position: "Defender",
    nationality: "Argentina",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Tyrell",
    last_name: "Malacia",
    position: "Defender",
    nationality: "Netherlands",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Raphael",
    last_name: "Varane",
    position: "Defender",
    nationality: "France",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Diogo",
    last_name: "Dalot",
    position: "Defender",
    nationality: "Portugal",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Luke",
    last_name: "Shaw",
    position: "Defender",
    nationality: "England",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Aaron",
    last_name: "Wan-Bissaka",
    position: "Defender",
    nationality: "England",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Bruno",
    last_name: "Fernandes",
    position: "Midfielder",
    nationality: "Portugal",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Christian",
    last_name: "Eriksen",
    position: "Midfielder",
    nationality: "Denmark",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Casemiro",
    last_name: "Casemiro",
    position: "Midfielder",
    nationality: "Brazil",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Scott",
    last_name: "McTominay",
    position: "Midfielder",
    nationality: "Scotland",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Kobbie",
    last_name: "Mainoo",
    position: "Midfielder",
    nationality: "England",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Anthony",
    last_name: "Martial",
    position: "Forward",
    nationality: "France",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Marcus",
    last_name: "Rashford",
    position: "Forward",
    nationality: "England",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Antony",
    last_name: "Antony",
    position: "Forward",
    nationality: "Brazil",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Alejandro",
    last_name: "Garnacho",
    position: "Forward",
    nationality: "Argentina",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Amad",
    last_name: "Diallo",
    position: "Forward",
    nationality: "Cote D Ivoire",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Shola",
    last_name: "Shoretire",
    position: "Forward",
    nationality: "England",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Mason",
    last_name: "Mount",
    position: "Midfielder",
    nationality: "England",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Toby",
    last_name: "Collyer",
    position: "Midfielder",
    nationality: "England",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Omari",
    last_name: "Forson",
    position: "Midfielder",
    nationality: "England",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Jonny",
    last_name: "Evans",
    position: "Defender",
    nationality: "Northern Ireland",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Andre",
    last_name: "Onana",
    position: "Goalkeeper",
    nationality: "Cameroon",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Rasmus",
    last_name: "Hojlund",
    position: "Forward",
    nationality: "Denmark",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Altay",
    last_name: "Bayindir",
    position: "Goalkeeper",
    nationality: "Turkey",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Sofyan",
    last_name: "Amrabat",
    position: "Midfielder",
    nationality: "Morocco",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Habeeb",
    last_name: "Ogunneye",
    position: "Defender",
    nationality: "England",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Harry",
    last_name: "Amass",
    position: "Defender",
    nationality: "England",
    team: "Manchester United F.C.",
  },
  {
    first_name: "Stefan",
    last_name: "Ortega",
    position: "Goalkeeper",
    nationality: "Germany",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Ederson",
    last_name: "Ederson",
    position: "Goalkeeper",
    nationality: "Brazil",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Scott",
    last_name: "Carson",
    position: "Goalkeeper",
    nationality: "England",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Kyle",
    last_name: "Walker",
    position: "Defender",
    nationality: "England",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Rúben",
    last_name: "Dias",
    position: "Defender",
    nationality: "Portugal",
    team: "Manchester City F.C.",
  },
  {
    first_name: "John",
    last_name: "Stones",
    position: "Defender",
    nationality: "England",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Nathan",
    last_name: "Aké",
    position: "Defender",
    nationality: "Netherlands",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Manuel",
    last_name: "Akanji",
    position: "Defender",
    nationality: "Switzerland",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Rico",
    last_name: "Lewis",
    position: "Defender",
    nationality: "England",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Jack",
    last_name: "Grealish",
    position: "Midfielder",
    nationality: "England",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Rodri",
    last_name: "Rodri",
    position: "Midfielder",
    nationality: "Spain",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Kevin",
    last_name: "De Bruyne",
    position: "Midfielder",
    nationality: "Belgium",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Bernardo",
    last_name: "Silva",
    position: "Midfielder",
    nationality: "Portugal",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Sergio",
    last_name: "Gómez",
    position: "Midfielder",
    nationality: "Spain",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Phil",
    last_name: "Foden",
    position: "Midfielder",
    nationality: "England",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Erling",
    last_name: "Haaland",
    position: "Forward",
    nationality: "Norway",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Julián",
    last_name: "Álvarez",
    position: "Forward",
    nationality: "Argentina",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Mateo",
    last_name: "Kovacic",
    position: "Midfielder",
    nationality: "Croatia",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Oscar",
    last_name: "Bobb",
    position: "Midfielder",
    nationality: "Norway",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Josko",
    last_name: "Gvardiol",
    position: "Defender",
    nationality: "Croatia",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Jérémy",
    last_name: "Doku",
    position: "Forward",
    nationality: "Belgium",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Matheus",
    last_name: "Nunes",
    position: "Midfielder",
    nationality: "Portugal",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Micah",
    last_name: "Hamilton",
    position: "Midfielder",
    nationality: "England",
    team: "Manchester City F.C.",
  },
  {
    first_name: "True",
    last_name: "Grant",
    position: "Goalkeeper",
    nationality: "England",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Max",
    last_name: "Alleyne",
    position: "Defender",
    nationality: "England",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Mahamadou",
    last_name: "Susoho",
    position: "Midfielder",
    nationality: "Spain",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Jacob",
    last_name: "Wright",
    position: "Midfielder",
    nationality: "England",
    team: "Manchester City F.C.",
  },
  {
    first_name: "Alisson",
    last_name: "Becker",
    position: "Goalkeeper",
    nationality: "Brazil",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Adrián",
    last_name: "Adrián",
    position: "Goalkeeper",
    nationality: "Spain",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Caoimhín",
    last_name: "Kelleher",
    position: "Goalkeeper",
    nationality: "Ireland",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Joe",
    last_name: "Gomez",
    position: "Defender",
    nationality: "England",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Virgil",
    last_name: "van Dijk",
    position: "Defender",
    nationality: "Netherlands",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Ibrahima",
    last_name: "Konaté",
    position: "Defender",
    nationality: "France",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Kostas",
    last_name: "Tsimikas",
    position: "Defender",
    nationality: "Greece",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Andy",
    last_name: "Robertson",
    position: "Defender",
    nationality: "Scotland",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Joël",
    last_name: "Matip",
    position: "Defender",
    nationality: "Cameroon",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Stefan",
    last_name: "Bajcetic",
    position: "Midfielder",
    nationality: "Spain",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Rhys",
    last_name: "Williams",
    position: "Defender",
    nationality: "England",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Trent",
    last_name: "Alexander-Arnold",
    position: "Defender",
    nationality: "England",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Thiago",
    last_name: "Alcântara",
    position: "Midfielder",
    nationality: "Spain",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Curtis",
    last_name: "Jones",
    position: "Midfielder",
    nationality: "England",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Harvey",
    last_name: "Elliott",
    position: "Midfielder",
    nationality: "England",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Bobby",
    last_name: "Clark",
    position: "Midfielder",
    nationality: "England",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Mohamed",
    last_name: "Salah",
    position: "Forward",
    nationality: "Egypt",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Cody",
    last_name: "Gakpo",
    position: "Forward",
    nationality: "Netherlands",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Diogo",
    last_name: "Jota",
    position: "Forward",
    nationality: "Portugal",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Luis",
    last_name: "Díaz",
    position: "Forward",
    nationality: "Colombia",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Darwin",
    last_name: "Núñez",
    position: "Forward",
    nationality: "Uruguay",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Ben",
    last_name: "Doak",
    position: "Forward",
    nationality: "Scotland",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Alexis",
    last_name: "Mac Allister",
    position: "Midfielder",
    nationality: "Argentina",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Dominik",
    last_name: "Szoboszlai",
    position: "Midfielder",
    nationality: "Hungary",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Fabian",
    last_name: "Mrozek",
    position: "Goalkeeper",
    nationality: "Poland",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Wataru",
    last_name: "Endo",
    position: "Midfielder",
    nationality: "Japan",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Jarell",
    last_name: "Quansah",
    position: "Defender",
    nationality: "England",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Ryan",
    last_name: "Gravenberch",
    position: "Midfielder",
    nationality: "Netherlands",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Conor",
    last_name: "Bradley",
    position: "Defender",
    nationality: "Northern Ireland",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Kaide",
    last_name: "Gordon",
    position: "Forward",
    nationality: "England",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Treymaurice",
    last_name: "Nyoni",
    position: "Midfielder",
    nationality: "England",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Thomas",
    last_name: "Hill",
    position: "Midfielder",
    nationality: "Wales",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Jayden",
    last_name: "Danns",
    position: "Forward",
    nationality: "England",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Amara",
    last_name: "Nallo",
    position: "Midfielder",
    nationality: "England",
    team: "Liverpool F.C.",
  },
  {
    first_name: "Mateusz",
    last_name: "Musialowski",
    position: "Forward",
    nationality: "Poland",
    team: "Liverpool F.C.",
  },

  {
    first_name: "Marcus",
    last_name: "Bettinelli",
    position: "Goalkeeper",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Benoît",
    last_name: "Badiashile",
    position: "Defender",
    nationality: "France",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Thiago",
    last_name: "Silva",
    position: "Defender",
    nationality: "Brazil",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Trevoh",
    last_name: "Chalobah",
    position: "Defender",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Ben",
    last_name: "Chilwell",
    position: "Defender",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Reece",
    last_name: "James",
    position: "Defender",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Marc",
    last_name: "Cucurella",
    position: "Defender",
    nationality: "Spain",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Wesley",
    last_name: "Fofana",
    position: "Defender",
    nationality: "France",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Alfie",
    last_name: "Gilchrist",
    position: "Defender",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Enzo",
    last_name: "Fernández",
    position: "Midfielder",
    nationality: "Argentina",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Mykhailo",
    last_name: "Mudryk",
    position: "Midfielder",
    nationality: "Ukraine",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Conor",
    last_name: "Gallagher",
    position: "Midfielder",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Carney",
    last_name: "Chukwuemeka",
    position: "Midfielder",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Raheem",
    last_name: "Sterling",
    position: "Forward",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Noni",
    last_name: "Madueke",
    position: "Forward",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Christopher",
    last_name: "Nkunku",
    position: "Forward",
    nationality: "France",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Levi",
    last_name: "Colwill",
    position: "Defender",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Malo",
    last_name: "Gusto",
    position: "Defender",
    nationality: "France",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Malang",
    last_name: "Sarr",
    position: "Defender",
    nationality: "France",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Nicolas",
    last_name: "Jackson",
    position: "Forward",
    nationality: "France",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Diego",
    last_name: "Moreira",
    position: "Forward",
    nationality: "Senegal",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Lesley",
    last_name: "Ugochukwu",
    position: "Midfielder",
    nationality: "Portugal",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Axel",
    last_name: "Disasi",
    position: "Defender",
    nationality: "France",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Robert",
    last_name: "Sánchez",
    position: "Goalkeeper",
    nationality: "Spain",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Moisés",
    last_name: "Caicedo",
    position: "Midfielder",
    nationality: "Ecuador",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Roméo",
    last_name: "Lavia",
    position: "Midfielder",
    nationality: "Spain",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Deivid",
    last_name: "Washington",
    position: "Forward",
    nationality: "Belgium",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Djordje",
    last_name: "Petrovic",
    position: "Goalkeeper",
    nationality: "Serbia",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Ishé",
    last_name: "Samuels-Smith",
    position: "Defender",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Cole",
    last_name: "Palmer",
    position: "Midfielder",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Ronnie",
    last_name: "Stutter",
    position: "Forward",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Josh",
    last_name: "Brooking",
    position: "Defender",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Leo",
    last_name: "Castledine",
    position: "Midfielder",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Dylan",
    last_name: "Williams",
    position: "Defender",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Michael",
    last_name: "Golding",
    position: "Midfielder",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Dujuan",
    last_name: "Richards",
    position: "Forward",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Ted",
    last_name: "Curd",
    position: "Goalkeeper",
    nationality: "Jamaica",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Max",
    last_name: "Merrick",
    position: "Goalkeeper",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Cesare",
    last_name: "Casadei",
    position: "Midfielder",
    nationality: "Italy",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Ollie",
    last_name: "Harrison",
    position: "Midfielder",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Billy",
    last_name: "Gee",
    position: "Midfielder",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Jimi",
    last_name: "Tauriainen",
    position: "Midfielder",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Harrison",
    last_name: "Murray-Campbell",
    position: "Defender",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Josh",
    last_name: "Acheampong",
    position: "Defender",
    nationality: "England",
    team: "Chelsea F.C.",
  },
  {
    first_name: "Teddy",
    last_name: "Sharman-Lowe",
    position: "Goalkeeper",
    nationality: "England",
    team: "Chelsea F.C.",
  },

  {
    first_name: "Fraser",
    last_name: "Forster",
    position: "Goalkeeper",
    nationality: "England",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Brandon",
    last_name: "Austin",
    position: "Goalkeeper",
    nationality: "England",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Alfie",
    last_name: "Whiteman",
    position: "Goalkeeper",
    nationality: "England",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Emerson",
    last_name: "Royal",
    position: "Defender",
    nationality: "Brazil",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Cristian",
    last_name: "Romero",
    position: "Defender",
    nationality: "Argentina",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Ben",
    last_name: "Davies",
    position: "Defender",
    nationality: "Wales",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Alfie",
    last_name: "Dorrington",
    position: "Defender",
    nationality: "England",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Oliver",
    last_name: "Skipp",
    position: "Midfielder",
    nationality: "England",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Pierre-Emile",
    last_name: "Højbjerg",
    position: "Midfielder",
    nationality: "Denmark",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Ryan",
    last_name: "Sessegnon",
    position: "Midfielder",
    nationality: "England",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Pape",
    last_name: "Sarr",
    position: "Midfielder",
    nationality: "Senegal",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Rodrigo",
    last_name: "Bentancur",
    position: "Midfielder",
    nationality: "Uruguay",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Yves",
    last_name: "Bissouma",
    position: "Midfielder",
    nationality: "Mali",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Son",
    last_name: "Heung-Min",
    position: "Forward",
    nationality: "South Korea",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Richarlison",
    last_name: "Richarlison",
    position: "Forward",
    nationality: "Brazil",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Jamie",
    last_name: "Donley",
    position: "Forward",
    nationality: "England",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Dejan",
    last_name: "Kulusevski",
    position: "Midfielder",
    nationality: "Sweden",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Pedro",
    last_name: "Porro",
    position: "Defender",
    nationality: "Spain",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Guglielmo",
    last_name: "Vicario",
    position: "Goalkeeper",
    nationality: "Italy",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "James",
    last_name: "Maddison",
    position: "Midfielder",
    nationality: "England",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Destiny",
    last_name: "Udogie",
    position: "Defender",
    nationality: "Italy",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Giovani",
    last_name: "Lo Celso",
    position: "Midfielder",
    nationality: "Argentina",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Bryan",
    last_name: "Gil",
    position: "Forward",
    nationality: "Spain",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Manor",
    last_name: "Solomon",
    position: "Forward",
    nationality: "Israel",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Micky",
    last_name: "van de Ven",
    position: "Defender",
    nationality: "Netherlands",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Brennan",
    last_name: "Johnson",
    position: "Forward",
    nationality: "Wales",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Yago",
    last_name: "Santiago",
    position: "Forward",
    nationality: "Spain",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Dane",
    last_name: "Scarlett",
    position: "Forward",
    nationality: "England",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Timo",
    last_name: "Werner",
    position: "Forward",
    nationality: "Germany",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Radu",
    last_name: "Dragusin",
    position: "Defender",
    nationality: "Romania",
    team: "Tottenham Hotspur F.C.",
  },
  {
    first_name: "Aaron",
    last_name: "Ramsdale",
    position: "Goalkeeper",
    nationality: "England",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Karl",
    last_name: "Hein",
    position: "Goalkeeper",
    nationality: "Estonia",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Ben",
    last_name: "White",
    position: "Defender",
    nationality: "England",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Gabriel",
    last_name: "Magalhães",
    position: "Defender",
    nationality: "Brazil",
    team: "Arsenal F.C.",
  },
  {
    first_name: "William",
    last_name: "Saliba",
    position: "Defender",
    nationality: "France",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Jakub",
    last_name: "Kiwior",
    position: "Defender",
    nationality: "Poland",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Takehiro",
    last_name: "Tomiyasu",
    position: "Defender",
    nationality: "Japan",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Thomas",
    last_name: "Partey",
    position: "Midfielder",
    nationality: "Ghana",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Bukayo",
    last_name: "Saka",
    position: "Forward",
    nationality: "England",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Martin",
    last_name: "Ødegaard",
    position: "Midfielder",
    nationality: "Norway",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Emile",
    last_name: "Smith Rowe",
    position: "Midfielder",
    nationality: "England",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Jorginho",
    last_name: "Jorginho",
    position: "Midfielder",
    nationality: "Italy",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Fábio",
    last_name: "Vieira",
    position: "Midfielder",
    nationality: "Portugal",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Mohamed",
    last_name: "Elneny",
    position: "Midfielder",
    nationality: "Egypt",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Oleksandr",
    last_name: "Zinchenko",
    position: "Defender",
    nationality: "Ukraine",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Mauro",
    last_name: "Bandeira",
    position: "Midfielder",
    nationality: "Portugal",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Ethan",
    last_name: "Nwaneri",
    position: "Midfielder",
    nationality: "England",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Gabriel",
    last_name: "Jesus",
    position: "Forward",
    nationality: "Brazil",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Gabriel",
    last_name: "Martinelli",
    position: "Forward",
    nationality: "Brazil",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Eddie",
    last_name: "Nketiah",
    position: "Forward",
    nationality: "England",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Leandro",
    last_name: "Trossard",
    position: "Forward",
    nationality: "Belgium",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Reiss",
    last_name: "Nelson",
    position: "Forward",
    nationality: "England",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Kai",
    last_name: "Havertz",
    position: "Midfielder",
    nationality: "Germany",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Jurriën",
    last_name: "Timber",
    position: "Defender",
    nationality: "Netherlands",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Declan",
    last_name: "Rice",
    position: "Midfielder",
    nationality: "England",
    team: "Arsenal F.C.",
  },
  {
    first_name: "David",
    last_name: "Raya",
    position: "Goalkeeper",
    nationality: "Spain",
    team: "Arsenal F.C.",
  },
  {
    first_name: "James",
    last_name: "Sweet",
    position: "Defender",
    nationality: "Wales",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Cédric",
    last_name: "Soares",
    position: "Defender",
    nationality: "Portugal",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Reuell",
    last_name: "Walters",
    position: "Defender",
    nationality: "England",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Amario",
    last_name: "Cozier-Duberry",
    position: "Midfielder",
    nationality: "England",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Myles",
    last_name: "Lewis-Skelly",
    position: "Midfielder",
    nationality: "England",
    team: "Arsenal F.C.",
  },
  {
    first_name: "Ayden",
    last_name: "Heaven",
    position: "Defender",
    nationality: "England",
    team: "Arsenal F.C.",
  },
];

export default PLAYERS;
